# Generated by Django 4.2 on 2023-04-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mijoz',
            name='geolocation_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
